# -*- coding: utf-8 -*-
"""DA3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtef_lXeP9PS2tSjzMmC7dEHWSUg2JND
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/iris.csv')
df.head()

df.tail()

df.describe()

df.info()

df.dtypes

df.species.unique()

mapi={'setosa':0,'versicolor':1,'virginica':2}
df=df.replace({'species':mapi})
df.head()

df.dtypes

df.isnull().sum()

x,y=df.iloc[:,:-1],df.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.35,random_state=0)

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(y_pred)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

import seaborn as sns
sns.heatmap(cm,annot=True)

print("\nDetailed Metrics per Class (One-vs-Rest):")
for i in range(len(np.unique(y_test))):
    TP = cm[i, i]

    FN = np.sum(cm[i, :]) - TP

    FP = np.sum(cm[:, i]) - TP

    TN = np.sum(cm) - (TP + FN + FP)

    print(f"\nClass {i} (label: {iris.target_names[i]} if iris dataset was used, otherwise just Class {i}):")
    print(f"  True Positives (TP): {TP}")
    print(f"  False Negatives (FN): {FN}")
    print(f"  False Positives (FP): {FP}")
    print(f"  True Negatives (TN): {TN}")

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

overall_accuracy = accuracy_score(y_test, y_pred)
overall_error_rate = 1 - overall_accuracy
overall_precision_macro = precision_score(y_test, y_pred, average='macro')
overall_recall_macro = recall_score(y_test, y_pred, average='macro')
overall_f1_macro = f1_score(y_test, y_pred, average='macro')

print("\nOverall Metrics:")
print(f"  Overall Accuracy: {overall_accuracy:.4f}")
print(f"  Overall Error Rate: {overall_error_rate:.4f}")
print(f"  Overall Precision : {overall_precision_macro:.4f}")
print(f"  Overall Recall : {overall_recall_macro:.4f}")
print(f"  Overall F1-Score : {overall_f1_macro:.4f}")