# -*- coding: utf-8 -*-
"""DataAnalytics2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTlqnY-MU60M3uC-1CVPnNknCYT0LXQx
"""

import pandas as pd
df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()

X = df.iloc[:, 2:4].values   # Age, Estimated Salary
y = df.iloc[:, 4].values     # Purchased

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n", cm)

# Extract TP, FP, TN, FN
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

print("\nTP:", TP)
print("FP:", FP)
print("TN:", TN)
print("FN:", FN)

# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)

# Error Rate
error_rate = (FP + FN) / (TP + TN + FP + FN)

# Precision
precision = TP / (TP + FP)

# Recall
recall = TP / (TP + FN)

print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)