# -*- coding: utf-8 -*-
"""dataVisualization2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ku_uMpAtyz6v-ckY1HvYLqIydB7YEI19
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

dataset=sns.load_dataset('titanic')
dataset.head()

dataset.info()

dataset.describe()

print("Survived: ",dataset['survived'].value_counts()[1])
print("Dead: ",dataset['survived'].value_counts()[0])

sns.boxplot(x='sex', y='age', data=dataset)
plt.show()

sns.boxplot(x='sex', y='age', hue='survived', data=dataset)
plt.show()