# -*- coding: utf-8 -*-
"""DataVisualization3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBPSs5qQmy7G334VKKFXPKy1NvpMyY7n
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/IRIS.csv')
df.head()

df.tail()

df.info()

df.describe()

df.dtypes

np.unique(df['species'])

sns.histplot(df['sepal_length'])

sns.histplot(df['sepal_width'])

sns.histplot(df['petal_length'])

sns.histplot(df['petal_width'])

sns.histplot(df['species'])

sns.boxplot(df['sepal_length'])

sns.boxplot(df['sepal_width'])

sns.boxplot(df['petal_length'])

sns.boxplot(df['petal_width'])

dataToPlot=[df['sepal_length'],df['sepal_width'],df['petal_length'],df['petal_width']]
fig=plt.figure(figsize=(12,8))
ax=fig.add_subplot(111)
plt.boxplot(dataToPlot)
plt.show()