# -*- coding: utf-8 -*-
"""DataAnalytics1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1887tOcpQeaR2GSDjA83towAhmmfLXN_o
"""

import pandas as pd
df=pd.read_csv("/content/BostonHousing.csv")
df

df.head()

x=df.drop('medv',axis=1)
y=df['medv']

x.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.25)
x_train

x_train.head()

x_train.shape

x_test.shape

print('Missing values in x_train:')
print(x_train.isnull().sum())
print('\nMissing values in x_test:')
print(x_test.isnull().sum())

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

# Fit on x_train['rm'] and transform both x_train['rm'] and x_test['rm']
x_train['rm'] = imputer.fit_transform(x_train[['rm']])
x_test['rm'] = imputer.transform(x_test[['rm']])

print('Missing values after imputation:')
print('Missing values in x_train:')
print(x_train.isnull().sum())
print('\nMissing values in x_test:')
print(x_test.isnull().sum())

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
lr.coef_

lr.intercept_

y_pred=lr.predict(x_test)
y_pred

y_pred.shape

result=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
result

residual_error=y_test-y_pred
residual_error

sum(residual_error)/len(residual_error)

from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_pred)

lr.score(x_test,y_test)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)