# -*- coding: utf-8 -*-
"""DataVisualization1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KT7y9TGOOJNquO_sUALDPYstd7O_XmwJ
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

dataset=sns.load_dataset('titanic')
dataset.head()

dataset.info()

dataset.shape

print("Survived: ", dataset['survived'].value_counts()[1])
print("Dead: ", dataset['survived'].value_counts()[0])

sns.countplot(x='survived', data=dataset)

sns.countplot(x='sex', data=dataset)

sns.countplot(x='pclass',data=dataset)

sns.histplot(dataset['age'])
plt.show()

sns.histplot(dataset['fare'])
plt.show()

sns.boxplot(x='sex', y='age', data=dataset)
plt.show()

sns.boxplot(x='sex', y='age', hue='survived', data=dataset)
plt.show()

sns.pairplot(data=dataset)
plt.show()

sns.distplot(dataset['age'])
plt.show()

sns.distplot(dataset['age'],kde=False)
plt.show()

sns.distplot(dataset['fare'])
plt.show()

sns.jointplot(x='age', y='fare', data=dataset)
plt.show()

sns.jointplot(x='age', y='fare', kind='hex', data=dataset)
plt.show()

sns.jointplot(x='age', y='fare', kind='kde', data=dataset)
plt.show()

sns.rugplot(dataset['age'])
plt.show()

sns.rugplot(dataset['fare'])
plt.show()

