# -*- coding: utf-8 -*-
"""DSBDA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_xWcIyZ5qL7uA-R9JaAYzqiKUUFmwkN
"""

import pandas as pd
import numpy as np
df = pd.read_csv("/academic_performance_dataset_V2.csv")
df.head()

df.isnull().sum()

df.describe(include='all')

df.shape

df.dtypes

# Convert object columns to categorical
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype('category')

df.dtypes

for col in df.select_dtypes(include='category').columns:
    df[col + "_code"] = df[col].cat.codes

df.head()